### ISSUE TITLE
Design test level

### ISSUE THREAD

**Issue by omn0mn0m** [nomniverse/DODGEBALL#4]

**Comment by shields2314** [comment]
![IMG_20200430_150522](https://user-images.githubusercontent.com/23392949/80749318-44413980-8af4-11ea-826f-dd0020dba536.jpg)

**Comment by shields2314** [comment]
Obviously done with my poor penmanship. But I figured a map design with multiple things to jump onto/ working your way to the top and then running down would be fun. I imagined playing tag while I drew it.
